FROM debian:latest
RUN apt-get update && apt-get install python3-pip -y 
RUN pip3 install opencv-python-headless==4.5.3.56

RUN mkdir /app
ADD requirements.txt /app/requirements.txt

ADD main.py /app/main.py
ADD PlantSpyModels.py /app/PlantSpyModels.py
ADD authenticate.py /app/authenticate.py
ADD authorisation.py /app/authorisation.py
ADD models /app/models
WORKDIR /app/

RUN pip install -r requirements.txt


CMD python3 main.py



# CMD ["uvicorn", "app.main:app", "--reload"]