name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build_and_run_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Docker
      run: |
        #sudo apt-get update # IEL : is it necessary all time ? : generates conflict between packages 
        #sudo apt-get install -y docker.io
        #sudo apt-get update
        #sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        #sudo docker run hello-world
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io
        
    - name : Install  docker-buildx plugin
      run: |
        DOCKER_BUILDX_VERSION="v0.10.4"
        BUILDX_DOWNLOAD_URL="https://github.com/docker/buildx/releases/download/$DOCKER_BUILDX_VERSION/buildx-$DOCKER_BUILDX_VERSION.linux-amd64"
        sudo curl -L $BUILDX_DOWNLOAD_URL -o /usr/local/bin/docker-buildx
        sudo chmod a+x /usr/local/bin/docker-buildx




    - name: Run setup.sh script
      run: |
        #chmod +x setup.sh
        #./setup.sh
