name: Deploy Docker Image to Docker Hub

on:
  push:
    branches: 
      - main

jobs:
  notify1:
    runs-on: ubuntu-latest
    steps:
      - name: Notify deployment started
        run: echo "Deployment started!"
  deploy:
    runs-on: ubuntu-latest
    needs: [Test_Model_Directly.test, Test_API_Docker.build_and_run_docker]

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile_plantspy --tag ${{ secrets.DOCKER_HUB_USERNAME }}/mlops_plantspy:1.0.1

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlops_plantspy:1.0.1

  notify2:
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
      - name: Notify deployment result
        run: echo "Deployment successful!"
